[package]
build = './common/build/build.rs'
description = 'DHT protocol library'
edition = '2021'
name = 'dht'
version = '0.6.87'

[dependencies]
adnl = { features = [ 'node' ], git = 'https://github.com/tonlabs/ever-adnl.git', tag = '0.9.22' }
async-trait = '0.1'
enum-as-inner = '=0.5.1'
failure = '0.1'
hex = '0.4'
lockfree = { git = 'https://github.com/tonlabs/lockfree.git' }
log = '0.4'
overlay = { git = 'https://github.com/tonlabs/ever-overlay.git', tag = '0.7.19' }
rand = '0.8'
tokio = { features = [ 'rt-multi-thread' ], version = '1.5' }
ton_api = { git = 'https://github.com/tonlabs/ever-tl.git', package = 'ton_api', tag = '0.3.59' }
ton_types = { git = 'https://github.com/tonlabs/ever-types.git', tag = '2.0.32' }

[features]
telemetry = [ 'adnl/telemetry', 'overlay/telemetry' ]

